src/EasyUITree/Models/ShcmeaModels/CompProgram.cs
using System;
using System.Collections.Generic;

namespace EasyUITree.Models.ShcmeaModels
{
    public partial class CompProgram
    {
        public int ProgId { get; set; }
        public string ProgNo { get; set; }
        public string ProgDesc { get; set; }
        public string ProgCategory { get; set; }
        public string ProgArea { get; set;}
        public string ProgController { get; set; }
        public string ProgAction { get; set; }
        public DateTime CreateDatetime { get; set; }
        public string CreateEmpId { get; set; }
        public DateTime ModifyDatetime { get; set; }
        public string ModifyEmpId { get; set; }

        public virtual CompTreeNode CompTreeNode { get; set; }
    }
}

src/EasyUITree/Models/ShcmeaModels/CompTreeNode.cs
using System;
using System.Collections.Generic;

namespace EasyUITree.Models.ShcmeaModels
{
    public partial class CompTreeNode
    {
        public int NodeId { get; set; }
        public int? ParNodeId { get; set; }
        public int ProgId { get; set; }
        public int Sort { get; set; }
        public int? Status { get; set; }
        public DateTime CreateDatetime { get; set; }
        public string CreateEmpId { get; set; }
        public DateTime ModifyDatetime { get; set; }
        public string ModifyEmpId { get; set; }

        public virtual CompProgram Node { get; set; }
        public virtual CompTreeNode ParNode { get; set; }
        public virtual ICollection<CompTreeNode> InverseParNode { get; set; }
    }
}

src/EasyUITree/Models/ShcmeaModels/MenuContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace EasyUITree.Models.ShcmeaModels
{
    public partial class MenuContext : DbContext
    {
        public virtual DbSet<CompProgram> CompProgram { get; set; }
        public virtual DbSet<CompTreeNode> CompTreeNode { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            #warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Menu;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CompProgram>(entity =>
            {
                entity.HasKey(e => e.ProgId)
                    .HasName("PK_CompProgram");

                entity.HasIndex(e => e.ProgNo)
                    .HasName("IK_CompProgram_ProgNo")
                    .IsUnique();

                entity.Property(e => e.ProgId).HasColumnName("ProgID");

                entity.Property(e => e.CreateDatetime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("getdate()");

                entity.Property(e => e.CreateEmpId)
                    .IsRequired()
                    .HasColumnName("CreateEmpID")
                    .HasColumnType("varchar(10)");

                entity.Property(e => e.ModifyDatetime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("getdate()");

                entity.Property(e => e.ModifyEmpId)
                    .IsRequired()
                    .HasColumnName("ModifyEmpID")
                    .HasColumnType("varchar(10)");

                entity.Property(e => e.ProgCategory)
                    .IsRequired()
                    .HasColumnType("varchar(1)");

                entity.Property(e => e.ProgDesc)
                    .IsRequired()
                    .HasColumnType("varchar(20)");

                entity.Property(e => e.ProgNo)
                    .IsRequired()
                    .HasColumnType("varchar(10)");
            });

            modelBuilder.Entity<CompTreeNode>(entity =>
            {
                entity.HasKey(e => e.NodeId)
                    .HasName("PK_CompTreeNode");

                entity.Property(e => e.NodeId)
                    .HasColumnName("NodeID")
                    .ValueGeneratedOnAdd();

                entity.Property(e => e.CreateDatetime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("getdate()");

                entity.Property(e => e.CreateEmpId)
                    .IsRequired()
                    .HasColumnName("CreateEmpID")
                    .HasColumnType("varchar(10)");

                entity.Property(e => e.ModifyDatetime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("getdate()");

                entity.Property(e => e.ModifyEmpId)
                    .IsRequired()
                    .HasColumnName("ModifyEmpID")
                    .HasColumnType("varchar(10)");

                entity.Property(e => e.ParNodeId).HasColumnName("ParNodeID");

                entity.Property(e => e.ProgId).HasColumnName("ProgID");

                entity.HasOne(d => d.Node)
                    .WithOne(p => p.CompTreeNode)
                    .HasForeignKey<CompTreeNode>(d => d.NodeId)
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_CompTreeNode_CompProgram");

                entity.HasOne(d => d.ParNode)
                    .WithMany(p => p.InverseParNode)
                    .HasForeignKey(d => d.ParNodeId)
                    .HasConstraintName("FK_CompTreeNode_CompTreeNode");
            });
        }
    }
}

src/EasyUITree/Models/ViewModels/CompTreeNode_ViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EasyUITree.Models.ViewModels
{
    public class CompTreeNode_ViewModel
    {
        public int NodeId { get; set; }
        public int? ParNodeId { get; set; }
        public int ProgId { get; set; }
        public int Sort { get; set; }
        public string ProgDesc { get; set; }
        public string ProgURL { get; set; }
        /*
        public string ProgArea { get; set; }
        public string ProgController { get; set; }
        public string ProgAction { get; set; }
        */
    }
}

src/EasyUITree/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using EasyUITree.Repositorys;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace EasyUITree.Controllers
{
    public class MenuController : Controller
    {
        private MenuTree_Repository _helper = new MenuTree_Repository();

        // GET: /<controller>/
        public IActionResult TreeLoadJson()
        {
            ViewBag.HasRootNode = this._helper.GetRootNode() != null ? "true" : "false";
            return View();
        }

        [HttpPost]
        public ActionResult GetTreeNodeJSON()
        {
            string result = this._helper.GetTreeJson();
            return Content(result, "application/json");
            //ViewBag.jsonData = this._helper.GetTreeJson();
            //return View();
        }
    }
}

src/EasyUITree/Views/Menu/GetTreeNodeJSON.cshtml
@{
    Layout = "~/Views/Shared/_TreeGridLayout.cshtml";
}
@ViewBag.jsonData

src/EasyUITree/Views/Menu/TreeLoadJson.cshtml
@{
    ViewBag.Title = "Tree, Load JSON";
    Layout = "~/Views/Shared/_TreeGridLayout.cshtml";
}

<h2>MenuTree - Json</h2>
<hr />
<div class="easyui-panel" style="padding:5px">
    <ul id="MenuTree" class="easyui-tree"></ul>
</div>
<input type="hidden" id="HasRootNode" name="HasRootNode" value="@ViewBag.HasRootNode" />

@section scripts
{
    <script type="text/javascript">
        $(document).ready(function () {

            var hasData = $.trim($('#HasRootNode').val()) === 'true';
            if (hasData) {
                $('#MenuTree').tree({
                    url: '@Url.Action("GetTreeNodeJSON", "Menu")',
                    onDblClick: function (node) {
                        if (node.attributes != '#') {
                            window.location.replace(node.attributes.url);
                        }


                    }
                });
            }
        });
    </script>
}

src/EasyUITree/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EasyUITree</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">EasyUITree</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - EasyUITree</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/EasyUITree/Views/Shared/_TreeGridLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Metismenu</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/easyui/themes/default/easyui.css" rel="stylesheet" />
        <link href="~/easyui/themes/icon.css" rel="stylesheet" />

    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div>
        @RenderBody()
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/easyui/jquery.easyui.min.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>